--- Makefile.org	2025-12-02 13:38:41.718280145 +0800
+++ Makefile	2025-12-02 13:49:46.790796168 +0800
@@ -1,10 +1,10 @@
 ifndef NAVISERVER
-    NAVISERVER  = /usr/local/ns
+    NAVISERVER  = /var/lib/naviserver
 endif
 
 include  $(NAVISERVER)/include/Makefile.module
 
 install:
-	$(INSTALL_SH) nsstats.tcl $(INSTSRVPAG)/	
-	$(INSTALL_SH) nsstats.adp $(INSTSRVPAG)/
-	$(INSTALL_SH) nsstats-4.99.adp $(INSTSRVPAG)/
+	$(INSTALL_SH) nsstats.tcl $(DESTDIR)$(INSTSRVPAG)/	
+	$(INSTALL_SH) nsstats.adp $(DESTDIR)$(INSTSRVPAG)/
+	$(INSTALL_SH) nsstats-4.99.adp $(DESTDIR)$(INSTSRVPAG)/
