--- Makefile.org	2025-12-05 17:25:53.447851522 +0800
+++ Makefile	2025-12-05 17:26:27.926439871 +0800
@@ -5,6 +5,6 @@
 include  $(NAVISERVER)/include/Makefile.module
 
 install:
-	$(INSTALL_SH) nsstats.tcl $(INSTSRVPAG)/	
-	$(INSTALL_SH) nsstats.adp $(INSTSRVPAG)/
-	$(INSTALL_SH) nsstats-4.99.adp $(INSTSRVPAG)/
+	$(INSTALL_SH) nsstats.tcl $(DESTDIR)$(INSTSRVPAG)/	
+	$(INSTALL_SH) nsstats.adp $(DESTDIR)$(INSTSRVPAG)/
+	$(INSTALL_SH) nsstats-4.99.adp $(DESTDIR)$(INSTSRVPAG)/
